# Generated by Django 4.2.1 on 2023-05-26 12:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('intern.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('intern.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('intership_id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='identifiant stage')),
                ('duration', models.DurationField(null=True, verbose_name='durée du stage')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annule', 'Annule')], max_length=30, verbose_name='statut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intern')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='identifiant projet')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('duration', models.DurationField(null=True, verbose_name='durée du stage')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annule', 'Annule')], max_length=30, verbose_name='statut')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intership')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='identifiant tâche')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('duration', models.DurationField(null=True, verbose_name='durée du stage')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annule', 'Annule')], max_length=30, verbose_name='statut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.project')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='identifiant phase')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('duration', models.DurationField(null=True, verbose_name='durée du stage')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annule', 'Annule')], max_length=30, verbose_name='statut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.project')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='identifiant document')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Autorisation de partage')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.phase')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.project')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.task')),
            ],
        ),
    ]
