# Generated by Django 4.2.1 on 2023-05-26 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_admin_intern_intership_project_task_phase_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='photo de profil'),
        ),
    ]
