# Generated by Django 4.2.1 on 2023-05-30 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern', '0002_alter_member_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Encadreur', 'Encadreur'), ('Stagiaire', 'Stagiaire')], default='Stagiaire', max_length=30, verbose_name="role de l'utilisateur")),
                ('photo', models.ImageField(default='defaultUserPicture.png', upload_to='', verbose_name='photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stagiaire',
                'verbose_name_plural': 'Stagiaires',
            },
        ),
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True, verbose_name='durée du stage(en semaines)')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annulé', 'Annulé')], max_length=30, verbose_name='statut')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intern')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('duration', models.IntegerField(null=True, verbose_name='durée du projet(en semaines)')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annulé', 'Annulé')], max_length=30, verbose_name='statut')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.intership')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='', verbose_name='photo de profil'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Encadreur', 'Encadreur'), ('Stagiaire', 'Stagiaire')], default='Encadreur', max_length=30, verbose_name="role de l'utilisateur")),
                ('photo', models.ImageField(default='defaultUserPicture.png', upload_to='', verbose_name='photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encadreur',
                'verbose_name_plural': 'Encadreurs',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('duration', models.IntegerField(null=True, verbose_name='durée de la tâche(en jours)')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annulé', 'Annulé')], max_length=30, verbose_name='statut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.project')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('duration', models.IntegerField(null=True, verbose_name='durée de la phase(en jours)')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annulé', 'Annulé')], max_length=30, verbose_name='statut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.project')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='titre')),
                ('description', models.CharField(max_length=5500, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Autorisation de partage')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.phase')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.project')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intern.task')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
