# Generated by Django 4.2.1 on 2023-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_intern_intership_project_alter_member_photo_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='role',
            field=models.CharField(choices=[('Stagiaire', 'Stagiaire')], default='Stagiaire', max_length=30, verbose_name="role de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='intership',
            name='end_date',
            field=models.DateField(null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='intership',
            name='start_date',
            field=models.DateField(null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='intership',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], max_length=30, verbose_name='etat'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='end_date',
            field=models.DateField(null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateField(null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], max_length=30, verbose_name='etat'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], max_length=30, verbose_name='etat'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], max_length=30, verbose_name='etat'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='role',
            field=models.CharField(choices=[('Encadreur', 'Encadreur')], default='Encadreur', max_length=30, verbose_name="role de l'utilisateur"),
        ),
    ]
