# Generated by Django 4.2.1 on 2023-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_alter_document_description_alter_intern_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='intership',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='intership',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de début'),
        ),
    ]
